//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunCat365.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunCat365.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GAME OVER.
        /// </summary>
        internal static string Game_GameOver {
            get {
                return ResourceManager.GetString("Game_GameOver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press space to play..
        /// </summary>
        internal static string Game_PressSpaceToPlay {
            get {
                return ResourceManager.GetString("Game_PressSpaceToPlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        internal static string Game_NewRecord
        {
            get
            {
                return ResourceManager.GetString("Game_NewRecord", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Endless Game.
        /// </summary>
        internal static string Menu_EndlessGame {
            get {
                return ResourceManager.GetString("Menu_EndlessGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FPS Max Limit.
        /// </summary>
        internal static string Menu_FPSMaxLimit {
            get {
                return ResourceManager.GetString("Menu_FPSMaxLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Menu_Information {
            get {
                return ResourceManager.GetString("Menu_Information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Launch at startup.
        /// </summary>
        internal static string Menu_LaunchAtStartup {
            get {
                return ResourceManager.GetString("Menu_LaunchAtStartup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open Repository.
        /// </summary>
        internal static string Menu_OpenRepository {
            get {
                return ResourceManager.GetString("Menu_OpenRepository", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Runner.
        /// </summary>
        internal static string Menu_Runner {
            get {
                return ResourceManager.GetString("Menu_Runner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }

        internal static string Menu_SpeedSource {
            get {
                return ResourceManager.GetString("Menu_SpeedSource", resourceCulture);
            }
        }

        internal static string Runner_Cat {
            get {
                return ResourceManager.GetString("Runner_Cat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string Runner_Horse {
            get {
                return ResourceManager.GetString("Runner_Horse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parrot.
        /// </summary>
        internal static string Runner_Parrot {
            get {
                return ResourceManager.GetString("Runner_Parrot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endless Game.
        /// </summary>
        internal static string Window_EndlessGame {
            get {
                return ResourceManager.GetString("Window_EndlessGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string SystemInfo_CPU {
            get {
                return ResourceManager.GetString("SystemInfo_CPU", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SystemInfo_User {
            get {
                return ResourceManager.GetString("SystemInfo_User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kernel.
        /// </summary>
        internal static string SystemInfo_Kernel {
            get {
                return ResourceManager.GetString("SystemInfo_Kernel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string SystemInfo_Available {
            get {
                return ResourceManager.GetString("SystemInfo_Available", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        internal static string SystemInfo_Memory {
            get {
                return ResourceManager.GetString("SystemInfo_Memory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string SystemInfo_Total {
            get {
                return ResourceManager.GetString("SystemInfo_Total", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string SystemInfo_Used {
            get {
                return ResourceManager.GetString("SystemInfo_Used", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string SystemInfo_Storage {
            get {
                return ResourceManager.GetString("SystemInfo_Storage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to C Drive.
        /// </summary>
        internal static string SystemInfo_DriveC {
            get {
                return ResourceManager.GetString("SystemInfo_DriveC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to D Drive.
        /// </summary>
        internal static string SystemInfo_DriveD {
            get {
                return ResourceManager.GetString("SystemInfo_DriveD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string SystemInfo_Network {
            get {
                return ResourceManager.GetString("SystemInfo_Network", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string SystemInfo_Sent {
            get {
                return ResourceManager.GetString("SystemInfo_Sent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string SystemInfo_Received {
            get {
                return ResourceManager.GetString("SystemInfo_Received", resourceCulture);
            }
        }

        internal static string SystemInfo_GPU {
            get {
                return ResourceManager.GetString("SystemInfo_GPU", resourceCulture);
            }
        }

        internal static string SystemInfo_Average {
            get {
                return ResourceManager.GetString("SystemInfo_Average", resourceCulture);
            }
        }

        internal static string SystemInfo_Maximum {
            get {
                return ResourceManager.GetString("SystemInfo_Maximum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tomato Clock.
        /// </summary>
        internal static string SystemInfo_TomatoClock {
            get {
                return ResourceManager.GetString("SystemInfo_TomatoClock", resourceCulture);
            }
        }
        
        internal static string Message_AppLaunched {
            get {
                return ResourceManager.GetString("Message_AppLaunched", resourceCulture);
            }
        }
        
        internal static string Message_Warning {
            get {
                return ResourceManager.GetString("Message_Warning", resourceCulture);
            }
        }
        
        internal static string Message_CPUUsageUnavailable {
            get {
                return ResourceManager.GetString("Message_CPUUsageUnavailable", resourceCulture);
            }
        }

        internal static string Menu_TomatoClockStart {
            get {
                return ResourceManager.GetString("Menu_TomatoClockStart", resourceCulture);
            }
        }

        internal static string Menu_TomatoClockPause {
            get {
                return ResourceManager.GetString("Menu_TomatoClockPause", resourceCulture);
            }
        }

        internal static string Menu_TomatoClockReset {
            get {
                return ResourceManager.GetString("Menu_TomatoClockReset", resourceCulture);
            }
        }

        internal static string Menu_TomatoClockDuration {
            get {
                return ResourceManager.GetString("Menu_TomatoClockDuration", resourceCulture);
            }
        }

        internal static string Message_TomatoClockCompleted {
            get {
                return ResourceManager.GetString("Message_TomatoClockCompleted", resourceCulture);
            }
        }
    }
}
